services:
  - type: web
    name: odds-backend
    env: node
    plan: free
    buildCommand: |
      npm install --legacy-peer-deps
      npm install -g @nestjs/cli
      npm run build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
